### ISSUE TITLE
Make sure that custom structs satisfying the "scalar arithmetic concept" can be used as types in `vector` and `matrix`

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/hlsl-specs#104]
**Is your feature request related to a problem? Please describe.**

Imagine that I declare a `spirv::uint8_t` SPIR-V type, then write a whole "wrapper" `uint8_t` struct which has all the operators we'd expect from a integer scalar.

OR I provide a polyfill to emulate a `float64_t` (like Mesa does) or `float16_t` (via the `half` library or `IlmBase`) on top of `uint64_t` or `uint16_t` respectively for when the DX12 implementation or Vulkan doesn't report support for arithmetic using these floating point types.

This is assuming https://github.com/microsoft/DirectXShaderCompiler/pull/4133 would get undone and proposal 0006 was implemented.

**Describe the solution you'd like**

HLSL built-in templates `vector` and `matrix` to work with any trivial and copyable `T` that defines same operators that a regular `float32_t`, `uint32_t` and `int32_t` do (in C++20 parlance, satisfies some concept we name).

**Describe alternatives you've considered**

Just grabbing GLM and using that to emulate the "non-native" types (if it would compile at all).

**Additional context**
#97 and the DXC issues I link within.

**Comment by llvm-beanz** [comment]
The HLSL vector type cannot be used with user-defined types and should not be allowed with them in the future.

By definition the underlying type of a vector must be a built-in floating point or integer type, and we should not relax that requirement just to work around a different limitation in the language that we should otherwise consider addressing.
