### ISSUE TITLE
HLSL feature: Support for inout/out like C# ref

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/hlsl-specs#28]
**Is your feature request related to a problem? Please describe.**
The code clarity is sometimes lacking when using the inout and out keywords, because while reading the code it's unclear that the function will be reading and/or writing to a keyword.

**Describe the solution you'd like**
I'd like a solution like C#'s ref keyword. This makes it so you have to say "ref myVar" instead of "myVar" when you pass it. So in HLSL this would be out or inout prefix. This could of course be a warning since it would break backwards compatibility, the user could then treat this warning as an error if they deem it important.

**Describe alternatives you've considered**
For "out" it'd be possible to return a struct of course, but I have to support other technical artists that might not do that and I still want to enforce readability. For inout it'd require them (and me) to pass and return the same struct, which is kind of painful.

**Additional context**
Moved the issue from https://github.com/microsoft/DirectXShaderCompiler/issues/4907#issuecomment-1369604539

**Comment by llvm-beanz** [comment]
This feature is inconsistent with the [current direction for HLSL]([https://github.com/microsoft/hlsl-specs/blob/main/docs/HLSL202x.md)](https://github.com/microsoft/hlsl-specs/blob/main/docs/HLSL202x.md).), so we're not going to move forward with it at this time.

It is probably a little confusing that HLSL's `in` and `out` keywords match C#, but they mean different things in the language. HLSL's `out` and `inout` parameters aren't references (passed by address) they're actually copied in and out of the function. Adding a `ref` keyword would be further confusing because they aren't references...

We do have a [proposal for adding C++ references](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0006-reference-types.md), which we're considering for an upcoming language version.

That doesn't address your request for call site validation, but I'm not sure how we would do that in a way that is consistent with the language direction.

**Comment by Nielsbishere** [comment]
@llvm-beanz ah okay. But if a keyword could be considered in that update it'd be great. It could check the function signature if the parameter is defined as a ref and if it is, it could give a warning if the param's name is not prefixed by ref. I think it'd be very useful to avoid confusion, especially important when working with a large shader codebase with lots of includes, so for our company it'd definitely be a nice to have, though I guess I could use a macro (or define) and mandate it by our code style guide.
