### ISSUE TITLE
[0010] vk::BufferPointer linked list example: legal HLSL? (copy constructor and recursive struct definition)

### ISSUE THREAD

**Issue by danbrown-amd** [microsoft/hlsl-specs#322]
**Which document does this relate to?**
[Buffer Pointers in HLSL With vk::BufferPointer](https://github.com/microsoft/hlsl-specs/blob/9c42e278961dbf5b77d7d18b1e7ba7f6c0856154/proposals/0010-vk-buffer-ref.md)

**Describe the issue you see with the spec**
The example under [Linked Lists and Local Variables](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0010-vk-buffer-ref.md#linked-lists-and-local-variables) relies on language features that currently are neither supported by dxc nor addressed in the draft [HLSL spec](https://microsoft.github.io/hlsl-specs/):

1. The recursive definition for `struct block_s` fails due to the attempt to instantiate the then-incomplete template argument of `vk::BufferPointer` (i.e. `struct block_s` itself) at the declaration of `next`.  A comment in SemaTemplate.cpp indicates that dxc's behavior here comports with the C++ standard:
```
    // C++ [temp.explicit]p3:
    //   A definition of a member class of a class template shall be in scope
    //   at the point of an explicit instantiation of the member class.
```

2. dxc does not support the C++-style syntax used in the first line of `MainPs` to invoke the copy constructor:
```
block_p g_p(g_PushConstants.root);
```
The error issued in this case is "unknown type name 'g_PushConstants'".  It appears that dxc recognizes a statement starting with a type name, another identifier, and a left parenthesis as the beginning of a function definition, and so an identifier after the left parenthesis is assumed to be a type name.

The latter issue could be regarded as an implementation oversight.  Fixing the former would require further divergence from C++.

**Comment by s-perron** [comment]
The DXC maintainers discussed this on Monday.

1. For the forward declaration issue. HLSL uses the same forward declaration rules as C++. In general, C++ does not disallow the use of incomplete types as templates, and neither does HLSL. Whether or not it is allows depends on how it is used. Since the buffer pointer proposal explicitly allows the use of incomplete type as the template for `vk::BufferPointer`, there should be no need to update the spec on this point. The remaining issue is how to implement this. We can discuss this more once the DXC pr has been opened.

2. For the constructor, you are correct the sample in the proposal will not work. I will update that. I will change it to

```
block_p g_p = block_p(g_PushConstants.root);
```

This type of syntax works for structs already: https://godbolt.org/z/4KTK1M4KG

**Comment by danbrown-amd** [comment]
With regard to the forward declaration issue: is the failure of [this example](https://godbolt.org/z/cEz9b83sz) due to a bug, a violation of the (anticipated) standard, or the absence of some capability intended for future implementation?

**Comment by s-perron** [comment]
> With regard to the forward declaration issue: is the failure of [this example](https://godbolt.org/z/cEz9b83sz) due to a bug, a violation of the (anticipated) standard, or the absence of some capability intended for future implementation?

In general, forward references are allowed, but there are specific uses of incomplete type that are not allowed. For RWBuffer, I believe it was never considered or tests if the template type needs to be complete.  It does work for other types like `vk::SpirvOpaqueType`. See https://godbolt.org/z/Gc7PfoEdf.

So for the RWBuffer case, it may or may not be a bug. There is no spec to point to in order to say what should happen. However, I can say it is not due to the absence of some capability intested for future implementation. It was just never considered. @pow2clk Please correct me if I am wrong on this point.

However, we know it is allowed for `vk::BufferPointer`. At this point, we would need to figure out the implementation. I would try to implement it in a way that RequireCompleteTypeImpl returns because the `vk::BufferPointer` is considered complete even if the template is incomplete. You might be able to use `vk::SpirvOpaqueType` as a model.

https://github.com/microsoft/DirectXShaderCompiler/blob/75ff50caa046a054747ae15b5c1910a4c8aa1917/tools/clang/lib/Sema/SemaType.cpp#L6671

**Comment by danbrown-amd** [comment]
> In general, forward references are allowed, but there are specific uses of incomplete type that are not allowed. For RWBuffer, I believe it was never considered or tests if the template type needs to be complete. It does work for other types like `vk::SpirvOpaqueType`. See https://godbolt.org/z/Gc7PfoEdf.

Note however that if you actually try to instantiate a `struct s`, dxc will crash with a stack overflow because `LowerTypeVisitor` can't handle the recursive type.  Still, it's good to know that HLSL parsing and type checking succeed in that case.
