### ISSUE TITLE
Eliminate hlsl `literal` types

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#73]
**Is your feature request related to a problem? Please describe.**
HLSL literal types are magic. They convert through odd rules that are inscrutable to define, and often result in promotions to sizes larger than the user wants.

**Describe the solution you'd like**
Adopt C/C++ literal prefix rules and implicit conversion rules.

**Describe alternatives you've considered**
Fixing the issues with literal types seems unnecessarily complicated and would result in further confusion by users.

**Additional context**
Some recent bugs:

[vector of int64 instead of int32](https://godbolt.org/z/MMbYxP9cW)
```hlsl
RWByteAddressBuffer buffer : register(u0, space0); 
[numthreads(1, 1, 1)]
void main() {
    buffer.Store4(0, 0.xxxx);
}
```

[Some odd doubles](https://godbolt.org/z/hPWf5cfa5)
```hlsl
[numthreads(1, 1, 1)]
void main() {
  int b;
  bool c;
  float a = (b == 0 ? 38 : 32) * (c ? 0.05 : 1.0);
}
```

**Comment by KStocky** [comment]
I shall add to this.

This will not compile https://shader-playground.timjones.io/48171e474758a6dc0f099fd9ca4c19c2 because a literal int and int are treated as different types.

However, Literal Int decays very easily to int when queried with some template metaprogramming. E.g. https://shader-playground.timjones.io/48064aafe35c1381d5afaee168525f7b

This is a valid workaround, however, I feel it should not be necessary.

I don't feel like devs should have to use enable_if everywhere to ensure that two types are in fact the same type.

**Comment by llvm-beanz** [comment]
I've posted a spec PR that addresses this in the language spec by adopting the behavior that is documented on Microsoft's HLSL docs rather than the behavior that DXC implements:

https://github.com/microsoft/hlsl-specs/pull/175

We should consider implementing this behavior in DXC as part of HLSL 202x (it should be a pretty simple change to DXC).

**Comment by llvm-beanz** [comment]
As per the discussion in #211, proposal [0017 - Conforming Literals](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0017-conforming-literals.md) has been accepted and merged into DXC as https://github.com/microsoft/DirectXShaderCompiler/pull/6572.

With this change `literal` types are no longer part of HLSL as of 202x.
