### ISSUE TITLE
[0010] Fix the address space for BufferPointers

### ISSUE THREAD

**Issue by s-perron** [microsoft/hlsl-specs#98]
**Which proposal does this relate to?**
[Proposal 0010: vk::BufferPointer](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0010-vk-buffer-ref.md)

**Describe the issue or outstanding question.**

The spec says 

> All buffer pointers are presumed to point into the host memory address space.

This is not correct. The pointers will contain the address of a buffer that can be used by the device to access the buffer. ~in device memory. That is, the address that is used by the device to access the buffer.~ **EDIT: @jeremyong pointed out my careless wording.**  The memory could be located on the device or simply accessible to the device. The shader does not know or care.

**Additional context**

See https://github.com/microsoft/hlsl-specs/issues/84#issuecomment-1713976696 and the follow up comments by @natevm and me.

The values for these pointers come from calls to [vkGetBufferDeviceAddress](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferDeviceAddressEXT.html) on the host. If we were to keep the language the same as vulkan, we would say that it is in the "device address space". I am open to other suggestions.

**Comment by s-perron** [comment]
FYI: @greg-lunarg

**Comment by natevm** [comment]
> In particular, you could have host-local memory addressable by the GPU in the device address space. Alternatively, with resizable bar, you could have device-local memory addressable by the CPU in the host address space.

if it is in device address space, then it is device-local memory, not host-local. If it’s allocated with resizable bar, then I believe this is still device-local memory.

So, there isn’t a distinction, because the locality and address space are the same afaik, at least with Vulkan. I could be wrong, @s-perron probably knows better than me.

These are both also different from “visibility” and “coherency”. 

I’d recommend reading this post which covers the complexity of memory terminology in Vulkan fairly well: 

https://asawicki.info/news_1740_vulkan_memory_types_on_pc_and_how_to_use_them

**Comment by jeremyong** [comment]
I've read that article (and the vulkan spec on this topic, albeit years ago) so I'll assume there's something I don't understand, but I assumed that address spaces mapped to the same physical memory via different MMUs was possible.

**Comment by natevm** [comment]
This page is also helpful: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetBufferDeviceAddress.html

> If multiple [VkBuffer](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkBuffer.html) objects are bound to overlapping ranges of [VkDeviceMemory](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDeviceMemory.html), implementations may return address ranges which overlap. In this case, it is ambiguous which [VkBuffer](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkBuffer.html) is associated with any given device address. 

So, ultimately this is something that is implementation specific.

**Comment by jeremyong** [comment]
Sorry, I think I'm not quite following. This issue, at least as I read it (@s-perron feel free to elaborate) pertains to _address spaces_, which I interpret differently from "address" and "location". Specifically, if I have an address, the value might be meaningful when dereferenced through a specific MMU (i.e. device or host). I liken this to DX12's notion of shader-visibility and CPU vs GPU handles, in addition to the notion of the "GPU address" of any given resource. Whether or not the address is defined in terms of a host or device address _space_ has no bearing on the physical location of that memory. The question that I'm not sure you addressed is this statement:

> if it is in device address space, then it is device-local memory, not host-local.

Why is this true? I don't see why host-local memory isn't visible over the PCIe bus, addressable in a device itself.

>  If it’s allocated with resizable bar, then I believe this is still device-local memory.

Yes it's of course device-local memory, but the point is that this memory has at least two valid addresses, one in the device address space, and one in the host address space.

**Comment by natevm** [comment]
> if it is in device address space, then it is device-local memory, not host-local.
> 
> Why is this true? I don't see why host-local memory can't be made visible over the PCIe bus, addressable by the device itself.

Your definition of "address spaces" sounds similar to what vulkan describes as "visibility". Memory that is host-local and both host and device visible can be accessed by both the CPU and the GPU. 

> If it’s allocated with resizable bar, then I believe this is still device-local memory.
> 
> Yes it's of course device-local memory, but the point is that this memory has at least two valid addresses, one in the device address space, and one in the host address space.

Kinda... With Vulkan, if you want to access memory on the host, then you cannot use Vulkan's vkDeviceAddress values. Instead, you map the memory to a pointer on the host. You would never upload a host-side mapped pointer to the device.

**Comment by jeremyong** [comment]
> Your definition of "address spaces" sounds similar to what vulkan describes as "visibility"

Sure, that's one way to interpret it (FWIW, I'm a heavy Vulkan user also).

> Again, can only use the mapped pointer on the host, and the device address handle on the device. They aren't interchangable.

Yes of course, but, and again, apologies for sounding like a broken record, you aren't answering my question about this statement:

> if it is in device address space, then it is device-local memory, not host-local.

In what sense are you referring to "address space" here for this statement to be true?

**Comment by natevm** [comment]
> Yes of course, but, and again, apologies for sounding like a broken record, you aren't answering my question about this statement:
> 
> if it is in device address space, then it is device-local memory, not host-local.
> 
> In what sense are you referring to "address space" here for this statement to be true?

I misunderstood what you meant by address spaces. 

An address space is the range of virtual addresses that some system assigns to a running program. Within the scope of a Vulkan program, there is only one address space for VkDeviceAddresses. If my VkDeviceAddress is 42, and another is 1337, it's a guarantee that both of those addresses still belong to the same "Vulkan Device Addresses" space. 

Your shader code will never need to answer the question "what address space does this value '42' live?" because it's always lives in the same "Vulkan vkDeviceAddress" space. 

(You might get multiple address spaces with multi-gpu configurations) 

These addresses are of course virtual, and virtual address spaces can map to other virtual address spaces. Because they are virtual, their physical locality can be either the host or the device. But that's locality, not "address space".

**Comment by natevm** [comment]
So, long and short of it, the issue with the spec is that it's talking about address spaces as if they were address localities, and then it confuses "host" (the CPU) for "device" (the GPU)

**Comment by jeremyong** [comment]
> Within the scope of a Vulkan program, there is only one address space for VkDeviceAddresses. If my VkDeviceAddress is 42, and another is 1337, it's a guarantee that both of those addresses still belong to the same "Vulkan Device Addresses" space.

I think you mean to say that there is an address space per `VkDevice` associated with the device MMU, since it's quite possible to have multiple devices within a program. Otherwise, I agree that the "Buffer Pointers and Address Space" section doesn't really make sense.

Note that there is a non-standard way in which some DXC docs refer to address space as well. Sometimes, it seems to be used to refer to memory "tier" for lack of a better word. That is, memory that allocated from the register file and memory allocated from LDS are different "spaces" in the sense that they are physically located in different tiers of the device-local memory hierarchy.

A natural question then might be, if I can form a `vk::BufferPointer` to a variable, is it legal to do so for a `groupshared` variable? Is it possible to write a function that accepts a `vk::BufferPointer` parameter, where the arg may refer to LDS or VRAM?

**Comment by s-perron** [comment]
I think part of the problem we have is the definition of the term "address space". This is not defined in Vulkan.

In LLVM an address space is just a number, and its interpretation is determined by the target. If we introduce a term like "device address space" to HLSL, we get to decide what it means. I suggested this because the Vulkan spec refers to the value that will be used for the buffer pointers as device addresses. This creates a similarly between the two.

As this discussion shows it is possible that this will be confusing. It is not a stretch to guess that a "device address" or "device address space" will be an address of a memory location in the device's local memory. However that does not have to be the case, at least the way that Vulkan uses the term device local".

Consider the NVIDIA memory layout mentioned in the [link](https://asawicki.info/news_1740_vulkan_memory_types_on_pc_and_how_to_use_them) above:

```
Heap 0: DEVICE_LOCAL
  Size = 8,421,113,856 B
  Type 0: DEVICE_LOCAL
  Type 1: DEVICE_LOCAL
Heap 1
  Size = 8,534,777,856 B
  Type 0
  Type 1: HOST_VISIBLE, HOST_COHERENT
  Type 2: HOST_VISIBLE, HOST_COHERENT, HOST_CACHED
```

It is possible to allocate memory on Heap 1 with memory type 1 or 2, bind a buffer to it, and then get the device address for that buffer. Using the Vulkan terms, you cannot call that address "device local" because it does not have the "device local" flag. However, I want to define "device address space" so that it will include that address.

I am open to alternatives. I am bad at naming things because I lack imagination. I am not sure of a better name for "an address that can be by the device to access the memory."

I hope this clears up the disagreement.

**Comment by s-perron** [comment]
@greg-lunarg Let me know if you have any better ideas.

**Comment by natevm** [comment]
At least personally, I like that terminology. I think it just needs to be clearly defined in the spec, similar to how you phrased it above.

**Comment by greg-lunarg** [comment]
The term "host memory address space" was requested and approved by @llvm-beanz in #53. Since this is an HLSL proposal, I deferred to the HLSL/DirectX expert for the correct terminology.

I think this term is fine in that it implies an address space not in the GPU address space.

If we were to use a Vulkan term, I would say Buffer Device Address space, which jives with @s-perron 's reference to vkGetBufferDeviceAddress.

I will create a PR to add the following to the sentence in question: "in DirectX parlance, or buffer device address space in Vulkan parlance". If @llvm-beanz doesn't like it, he can delete it.

**Comment by natevm** [comment]
> I think this term is fine in that it implies an address space not in the GPU address space.

No, it implies that the addresses are in the host address space, which is wrong. The addresses are a Vulkan address space which point to either host or device memory.

> If we were to use a Vulkan term, I would say Buffer Device Address space, which jives with @s-perron 's reference to vkGetBufferDeviceAddress.

This sounds good to me. 

> in DirectX parlance, or buffer device address space in Vulkan parlance

It’s not about parlance, it’s what’s true and what’s not true. Direct X doesn’t have a parlance for this, since Direct X doesn’t have device addresses. Still, if Direct X did have them, they wouldn’t be restricted to a “host address space” either.

**Comment by s-perron** [comment]
FYI: If we want to keep the language in line with the address spaces that Chris is already thinking about, I still think that "device memory" or device address space are best. See https://github.com/microsoft/hlsl-specs/pull/94/files#diff-29269dd46a5c0ae5cce91d3af91fce8d966c04887b38fe30ec54cb37cb28c5ceR230

@llvm-beanz Do you have any thoughts?

**Comment by llvm-beanz** [comment]
DirectX does have device addresses, we actually don't have host address support (see the [DXIL docs](https://github.com/microsoft/DirectXShaderCompiler/blob/93ad5b31316cfed379a8e83bb6cfbbc8bc886ff9/docs/DXIL.rst?plain=1#L1945)). We don't express them in HLSL, but we do in DXIL. DirectX and Vulkan both agree on the terminology for host and device memory, although the Vulkan memory model is specified clearly and the DXIL memory model is not (although as @s-perron pointed out I'm trying to fix that).

I approved the PR with "host address space" because that's what I thought you meant based on the proposal. If that isn't what was intended, we should correct it.

Since this proposal is Vulkan-specific I think it is appropriate to use terminology from the Vulkan memory model, and maybe we should also add a link to the Vulkan memory model documentation to provide additional context.

**Comment by greg-lunarg** [comment]
> Since this proposal is Vulkan-specific I think it is appropriate to use terminology from the Vulkan memory model, and maybe we should also add a link to the Vulkan memory model documentation to provide additional context.

OK. I will create a PR consistent with this ruling.
